services:
  client:
    image: dropnow-client
    build: ./client
    ports:
      - 3000:3000
  redis:
    image: dropnow-redis
    build: ./redis
  server:
    image: dropnow-server
    build: ./server
    ports:
      - 3001:3000
    depends_on:
      - redis
