name: DropNow CI

on:
    push:
        branches: [react]

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                port: ${{ secrets.PORT }}
                script: |
                    cd ./dropnow
                    git checkout .
                    git pull
                    git checkout react
                    ls
                    docker compose version
                    docker compose -f ./docker-compose.yml up -d --no-deps --build
